### ISSUE TITLE
Create GUI

### ISSUE THREAD

**Issue by Vazno** [Vazno/Image2MCBlock#2]
# The task is to create a GUI for main.py.
It can be done using:
- Flask, JavaScript, HTML & CSS
- or using some Python GUI framework.

###### The design should be modern.

**Comment by iyashk** [comment]
Hey, I am really looking forward to start with open source, and i want to do my first ever contribution, i really do have some experience on HTML, CSS and JS along with Flask which i used to do some projects. So if you please help me and give more information about the thing needed it would be better.

**Comment by Vazno** [comment]
> Hey, I am really looking forward to start with open source, and i want to do my first ever contribution, i really do have some experience on HTML, CSS and JS along with Flask which i used to do some projects. So if you please help me and give more information about the thing needed it would be better.

Hi, it's nice, what needs to be accomplished is GUI, where you can create blockerized minecraft image and videos, and configure this algorithm.
There should be a form that you can submit, and then the server returns you a result:
### The form:
- 'path_to_file', type=str (That can be a video or image)
- 'output_file', type=str (Name of the output file with it's type)

- '--filter' (Filter where you can choose blocks that will be included in making image e.g: https://rebane2001.com/mapartcraft/)
This is the json with all the blocks:
https://github.com/Vazno/Image2MCBlock/blob/main/blocks.json
One block looks like this:
```
    [
        "acacia_log", // It's a name
        48, // x 
        80, // y
        [ // RGB medians, doesn't matter
            105, 
            98,
            89
        ]
```
To get block images, there is a https://github.com/Vazno/Image2MCBlock/blob/main/minecraft_textures_atlas_blocks.png_0.png file with textures. (User can provide own textures '--png_atlas_filename', or use [this](https://github.com/Vazno/Image2MCBlock/blob/main) by default)

- '--scale_factor', type=int, default=0
- '--method', type=str, choices=["abs_diff", "euclidean"], default="euclidean" (Should be combo-box)
- '--png_atlas_filename', type=str, required=False (Just leave the entry-box value as "", and if someone provides )
- '--txt_atlas_filename', type=str, required=False (Just leave the entry-box value as "")

This is how it should look like (_but better_ ): https://rebane2001.com/mapartcraft/
Here is another reference:
https://mc-map.djfun.de/

So, what's your take on this? @iyashk

**Comment by iyashk** [comment]
Thank you for replying me back, From this I have understood that I shall be creating a flask app that simply accepts the image input and the optional features such as the filter, scale factor etc and finally outputs the file name and the type of the file name. And it should also display the image after the form has been submitted and an option for the user to download the result image. It that all?

**Comment by Vazno** [comment]
> Thank you for replying me back, From this I have understood that I shall be creating a flask app that simply accepts the image input and the optional features such as the filter, scale factor etc and finally outputs the file name and the type of the file name. And it should also display the image after the form has been submitted and an option for the user to download the result image. It that all?

Yes

**Comment by Shady2kOver** [comment]
I'm working on this as well 

could you tell me some more specifics bout what you want?
It could just be a simple form with the input output path , filtered blocks and a submit button right? or anything else?

and make it minecraft themed like the examples you provided?

**Comment by Shady2kOver** [comment]
It'd be nice if you could draw a sample for me in MS paint so I can get an idea, not super detailed just random squiggles , Im confused about the upload image part and everything

**Comment by Vazno** [comment]
> It'd be nice if you could draw a sample for me in MS paint so I can get an idea, not super detailed just random squiggles , Im confused about the upload image part and everything

![prototype](https://github.com/Vazno/Image2MCBlock/assets/96925396/b04f422b-865b-4498-95c1-baa5138ad489)
The filter part should take blocks positions and their names from blocks.json, and get it from https://github.com/Vazno/Image2MCBlock/blob/main/minecraft_textures_atlas_blocks.png_0.png as describer above, so that user can click and apply filters (blocks from which image or video will be made). Also add preview

**Comment by Shady2kOver** [comment]
![image](https://github.com/Vazno/Image2MCBlock/assets/67641632/dbe51399-1c23-44ac-9d8b-38872d5bcd39)
Here's a little idea of a very very basic prototype, this is literally my first time ever contributing lol its scary. Im not super experienced

**Comment by iridant** [comment]
Hey! Giving this a shot, I'll submit a PR soon.

**Comment by iridant** [comment]
Okay, I've submitted a [PR](https://github.com/Vazno/Image2MCBlock/pull/8).  Going to check out the other issues you have up on the board.
